version: "3.8"
docker:
      matrix:
        images: [ubuntu18.04, ubuntu20.04, ubuntu22.04, debian10, debian11]
services:
  main:
    build: .
    volumes:
      - .:/pwndbg
    platform: linux/amd64
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    
  
  ${{ matrix.images }}:
    build:
      context: . 
      dockerfile: Dockerfile-unitTests
      args:
        image: ${{ matrix.images }}
      target: ${{ matrix.images }}
    volumes:
      - .:/pwndbg
    platform: linux/amd64
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
