version: "3.8"
services:
  ubuntu18.04:
    build:
      context: . 
      target: ubuntu:18.04
    volumes:
      - .:/pwndbg
    platform: linux/amd64
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
      
  ubuntu20.04:
    build:
      context: . 
      target: ubuntu:20.04
    volumes:
      - .:/pwndbg
    platform: linux/amd64
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

  ubuntu22.04:
    build:
      context: . 
      target: ubuntu:22.04
    volumes:
      - .:/pwndbg
    platform: linux/amd64
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

  debian10:
    build:
      context: . 
      target: debian:10
    volumes:
      - .:/pwndbg
    platform: linux/amd64
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

  debian11:
    build:
      context: . 
      target: debian:11
    volumes:
      - .:/pwndbg
    platform: linux/amd64
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE