version: "3.8"
services:
  ubuntu18.04:
    build:
      context: . 
      dockerfile: Dockerfile-ubuntu18-04
      target: ubuntu18.04
    volumes:
      - .:/pwndbg
    platform: linux/amd64
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
      
  ubuntu20.04:
    build:
      context: . 
      dockerfile: Dockerfile-ubuntu20-04
      target: ubuntu20.04
    volumes:
      - .:/pwndbg
    platform: linux/amd64
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

  ubuntu22.04:
    build:
      context: . 
      dockerfile: Dockerfile-ubuntu22-04      
      target: ubuntu22.04
    volumes:
      - .:/pwndbg
    platform: linux/amd64
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

  debian10:
    build:
      context: . 
      dockerfile: Dockerfile-debian10
      target: debian10
    volumes:
      - .:/pwndbg
    platform: linux/amd64
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

  debian11:
    build:
      context: . 
      dockerfile: Dockerfile-debian11
      target: debian11
    volumes:
      - .:/pwndbg
    platform: linux/amd64
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE