name: Docker build
on: [push, pull_request]

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        images: [ubuntu18.04, ubuntu20.04, ubuntu22.04, debian10, debian11]

    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2

    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Docker Build Ubuntu ${{ matrix.version }}
      run: docker-compose build ${{ matrix.version }}

    - name: Test on Ubuntu ${{ matrix.version }}
      run: docker-compose run ${{ matrix.version }} ./tests.sh
